package com.simats.selfora.reports;

import com.simats.selfora.dto.ProgressDtos;
import com.simats.selfora.entity.Child;
import com.simats.selfora.exception.ResourceNotFoundException;
import com.simats.selfora.progress.ProgressAnalyticsService;
import com.simats.selfora.repository.ChildRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;

@Service
public class PdfReportService {

    @Autowired
    private ChildRepository childRepository;

    @Autowired
    private ProgressAnalyticsService progressAnalyticsService;

    public byte[] generateChildReportPdf(Long childId, Long activityId) {
        Child child = childRepository.findById(childId)
                .orElseThrow(() -> new ResourceNotFoundException("Child not found"));

        ProgressDtos.ProgressSummaryResponse progress = progressAnalyticsService.getProgressSummary(childId, activityId);

        StringBuilder sb = new StringBuilder();
        sb.append("=====================================================\n");
        sb.append("         SELFORA CLINICAL ADL EVALUATION REPORT       \n");
        sb.append("=====================================================\n\n");
        sb.append("CHILD NAME: ").append(child.getFirstName()).append(" ").append(child.getLastName()).append("\n");
        sb.append("DOB: ").append(child.getDateOfBirth()).append(" | GENDER: ").append(child.getGender()).append("\n");
        sb.append("DIAGNOSIS / CLINICAL NOTES: ").append(child.getDiagnosisNotes()).append("\n\n");

        sb.append("--- PERFORMANCE & INDEPENDENCE ANALYSIS ---\n");
        sb.append("TARGET ACTIVITY: ").append(progress.getActivityTitle()).append("\n");
        sb.append("OVERALL INDEPENDENCE: ").append(progress.getOverallIndependencePercentage()).append("%\n");
        sb.append("TOTAL THERAPY SESSIONS COMPLETED: ").append(progress.getTotalSessionsCompleted()).append("\n\n");

        sb.append("--- STEP-BY-STEP PROMPT BREAKDOWN ---\n");
        progress.getStepProgress().forEach(step -> {
            sb.append("Step ").append(step.getStepNumber()).append(": ").append(step.getStepTitle())
                    .append(" | Prompt: ").append(step.getCurrentPromptLevel())
                    .append(" | Independence: ").append(step.getIndependencePercentage()).append("%\n");
        });

        sb.append("\n--- GENERALIZATION ACROSS ENVIRONMENTS ---\n");
        progress.getGeneralizationProgress().forEach(env -> {
            sb.append("Environment: ").append(env.getEnvironment())
                    .append(" | Independence: ").append(env.getIndependencePercentage())
                    .append("% | Dominant Support: ").append(env.getDominantPromptLevel()).append("\n");
        });

        sb.append("\n=====================================================\n");
        sb.append("Generated by SELFORA Clinical Engine\n");

        return sb.toString().getBytes(StandardCharsets.UTF_8);
    }
}
